name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} cloud.canister.io:5000
      - name: Build
        run: docker build --build-arg port=3000 -t cloud.canister.io:5000/fahmialfareza/dzikir-app-frontend .
      - name: Push to registry
        run: docker push cloud.canister.io:5000/fahmialfareza/dzikir-app-frontend
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restart server
        run: >-
          curl --location --request POST 'https://api.github.com/repos/fahmialfareza/reverse-proxy-vps/dispatches' --header 'Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}' --header 'Accept: application/vnd.github.v3+json' --header 'Content-Type: application/json' --data-raw '{"event_type":"restart","client_payload":{"image":"cloud.canister.io:5000/fahmialfareza/dzikir-app-frontend","service_name":"server_dzikirapp-frontend"}}'
