name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} cloud.canister.io:5000
      - name: Build
        run: docker build --build-arg port=3000 -t cloud.canister.io:5000/fahmialfareza/dzikir-app-frontend .
      - name: Push to registry
        run: docker push cloud.canister.io:5000/fahmialfareza/dzikir-app-frontend
